name: vformer
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - libcxx
  - libffi
  - ncurses=6.3
  - openssl=1.1.1
  - pip=21.2.4
  - python=3.10.4
  - readline=8.1.2
  - setuptools=61.2.
  - sqlite=3.38.5
  - tk=8.6.12
  - tzdata=2022
  - wheel=0.37.
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - arrow==1.1.1
    - attrs==21.2.0
    - backports-entry-points-selectable==1.1.0
    - binaryornot==0.4.4
    - certifi==2021.5.30
    - cfgv==3.3.1
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - click==8.0.1
    - cookiecutter==1.7.3
    - distlib==0.3.2
    - einops==0.3.2
    - filelock==3.0.12
    - identify==2.2.13
    - idna==3.2
    - iniconfig==1.1.1
    - jinja2==3.0.1
    - jinja2-time==0.2.0
    - markupsafe==2.0.1
    - nodeenv==1.6.0
    - numpy==1.23.0
    - olefile==0.46
    - packaging==21.0
    - pillow==9.2.0
    - platformdirs==2.3.0
    - pluggy==1.0.0
    - poyo==0.5.0
    - pre-commit==2.15.0
    - py==1.10.0
    - pyparsing==2.4.7
    - pytest==7.1.2
    - python-dateutil==2.8.2
    - python-slugify==5.0.2
    - pyyaml==5.4.1
    - requests==2.26.0
    - six==1.16.0
    - text-unidecode==1.3
    - toml==0.10.2
    - tomli==2.0.1
    - torch==1.12.0
    - torchvision==0.13.0
    - typing-extensions==4.3.0
    - urllib3==1.26.6
    - virtualenv==20.7.2
