name: vformer
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.7.5=h06a4308_1
  - certifi=2021.5.30=py38h06a4308_0
  - cpuonly=1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - jpeg=9b=h024ee3a_2
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.3.0=h06a4308_520
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openjpeg=2.4.0=h3ad879b_0
  - openssl=1.1.1l=h7f8727e_0
  - pillow=8.3.1=py38h2c7a002_0
  - pip=21.0.1=py38h06a4308_0
  - python=3.8.11=h12debd9_0_cpython
  - pytorch=1.9.0=py3.8_cpu_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.10.0=py38_cpu
  - typing_extensions=3.10.0.0=pyhca03da5_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - arrow==1.1.1
    - attrs==21.2.0
    - backports-entry-points-selectable==1.1.0
    - binaryornot==0.4.4
    - cfgv==3.3.1
    - chardet==4.0.0
    - charset-normalizer==2.0.4
    - click==8.0.1
    - cookiecutter==1.7.3
    - distlib==0.3.2
    - einops==0.3.2
    - filelock==3.0.12
    - identify==2.2.13
    - idna==3.2
    - iniconfig==1.1.1
    - jinja2==3.0.1
    - jinja2-time==0.2.0
    - markupsafe==2.0.1
    - nodeenv==1.6.0
    - packaging==21.0
    - platformdirs==2.3.0
    - pluggy==1.0.0
    - poyo==0.5.0
    - pre-commit==2.15.0
    - py==1.10.0
    - pyparsing==2.4.7
    - pytest==6.2.5
    - python-dateutil==2.8.2
    - python-slugify==5.0.2
    - pyyaml==5.4.1
    - requests==2.26.0
    - six==1.16.0
    - text-unidecode==1.3
    - toml==0.10.2
    - urllib3==1.26.6
    - virtualenv==20.7.2
